import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Navigation } from "~/components/navigation";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from blackhole" });

  return (
    <>
      <Head>
        <title>Batnaidan | full-stack developer</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-[#001524]">
        <div className="container max-w-2xl">
          <Navigation />
          {/* <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p> */}
          <div id="home" className="flex min-h-screen flex-col justify-center">
            <div className="font-serif text-6xl italic text-[#ffecd1]">
              I<span className="text-[#ff7d00]">&apos;</span>m Full-stack
              developer
            </div>
            <div className="text-[#ffecd1]">
              22 year old (backend leaning) full-stack developer from
              Ulaanbaatar, Mongolia. Most of my experience is building
              customer-facing SaaS, websites and scalable Web Application.
            </div>
          </div>
          <div id="work">my work</div>
          <div id="blog">my blog</div>
          <div id="contact">contact</div>
        </div>
      </main>
    </>
  );
};

export default Home;
